/**
 * Curated News Sources Registry
 * 
 * Auto-generated from user's 273-source preferred list.
 * Maps source names and domains to tier/region/paywall metadata.
 */

import type { SourceEntry } from './news-search.js';

// ============================================================================
// Source name → domain lookup (for matching NewsMesh source names)
// ============================================================================

export const SOURCE_NAME_TO_DOMAIN: Record<string, string> = {
    "Africa News (Africanews)": "africanews.com",
    "Africa News": "africanews.com",
    "Al Arabiya English": "alarabiya.net",
    "Channel 4 News (Text)": "channel4.com",
    "Channel 4 News": "channel4.com",
    "Channel NewsAsia (CNA)": "channelnewsasia.com",
    "Channel NewsAsia": "channelnewsasia.com",
    "ITV News": "itv.com",
    "Sky News (UK)": "news.sky.com",
    "Sky News": "news.sky.com",
    "Caixin Global": "caxinglobal.com",
    "Mint": "livemint.com",
    "Nikkei Asia": "asia.nikkei.com",
    "Nikkei Asia (Politics)": "asia.nikkei.com",
    "FiveThirtyEight": "fivethirtyeight.com",
    "Buenos Aires Times": "batimes.com.ar",
    "NOTUS": "notus.com",
    "News24": "news24.com",
    "Taiwan News": "taiwannews.com.tw",
    "The Cable (Nigeria)": "thecable.ng",
    "The Cable": "thecable.ng",
    "The Dispatch (News)": "thedispatch.com",
    "The Dispatch": "thedispatch.com",
    "The Print": "theprint.in",
    "The Times of Israel": "timesofisrael.com",
    "The Independent": "independent.co.uk",
    "East Asia Forum": "eastasiaforum.org",
    "Just Security": "justsecurity.org",
    "Lawfare": "lawfaremedia.org",
    "Tech Policy Press": "techpolicy.press",
    "The Conversation": "theconversation.com",
    "The Conversation Africa": "theconversation.com",
    "War on the Rocks": "warontherocks.com",
    "Africa Check": "africacheck.org",
    "Full Fact": "fullfact.org",
    "PolitiFact": "politifact.com",
    "Semafor": "semafor.com",
    "Agence France-Presse (AFP)": "france24.com",
    "Agence France-Presse": "france24.com",
    "Associated Press (AP)": "apnews.com",
    "Associated Press": "apnews.com",
    "Bloomberg News": "bloomberg.com",
    "Deutsche Presse-Agentur (dpa)": "dpa-international.com",
    "Deutsche Presse-Agentur": "dpa-international.com",
    "Reuters": "reuters.com",
    "EU Agency for Cybersecurity (ENISA) News": "enisa.europa.eu",
    "EU Agency for Cybersecurity": "enisa.europa.eu",
    "CISA Alerts": "cisa.gov",
    "UK NCSC Blog": "ncsc.gov.uk",
    "openDemocracy": "opendemocracy.net",
    "New Lines Magazine": "newlinesmag.com",
    "Asia Sentinel": "asiasentinel.com",
    "Daily Maverick": "dailymaverick.co.za",
    "EUobserver": "euobserver.com",
    "Hromadske International": "hromadske.ua",
    "Kyiv Independent": "kyivindependent.com",
    "Meduza": "meduza.io",
    "Moscow Times": "themoscowtimes.com",
    "Novaya Gazeta Europe": "novayagazeta.eu",
    "Premium Times": "premiumtimesng.com",
    "Rappler": "rappler.com",
    "Scroll.in": "scroll.in",
    "The Continent": "thecontinent.org",
    "The Wire (India)": "thewire.in",
    "The Wire": "thewire.in",
    "Times of Central Asia": "timesca.com",
    "AP Newsroom Investigations": "apnews.com",
    "ICIJ": "icij.org",
    "Investigate Europe": "investigate-europe.eu",
    "OCCRP": "occrp.org",
    "Balkan Insight (BIRN)": "balkaninsight.com",
    "Balkan Insight": "balkaninsight.com",
    "Balkan Investigative Reporting Network (BIRN)": "birn.eu",
    "Balkan Investigative Reporting Network": "birn.eu",
    "Coda Story": "codastory.com",
    "Correctiv (English selections)": "correctiv.org",
    "Correctiv": "correctiv.org",
    "El Faro (English)": "elfaro.net",
    "El Faro": "elfaro.net",
    "Follow the Money": "followthemoney.ng",
    "The Center for Climate Reporting": "ccreporting.org",
    "The Examination": "theexamination.org",
    "Reveal (Center for Investigative Reporting)": "revealnews.org",
    "Reveal": "revealnews.org",
    "The Intercept": "theintercept.com",
    "Gothamist": "gothamist.com",
    "Der Spiegel International": "spiegel.de",
    "Foreign Policy": "foreignpolicy.com",
    "Le Monde diplomatique (English)": "mondediplo.com",
    "Le Monde diplomatique": "mondediplo.com",
    "TIME Magazine": "time.com",
    "The Africa Report": "theafricareport.com",
    "The Atlantic": "theatlantic.com",
    "The New York Review of Books (Current Affairs)": "nybooks.com",
    "The New York Review of Books": "nybooks.com",
    "The New Yorker": "newyorker.com",
    "BMJ News": "bmj.com",
    "Amnesty International (News)": "amnesty.org",
    "Amnesty International": "amnesty.org",
    "Human Rights Watch (News)": "hrw.org",
    "Human Rights Watch": "hrw.org",
    "Focus Taiwan (CNA English)": "focustaiwan.tw",
    "Focus Taiwan": "focustaiwan.tw",
    "Interfax Ukraine (English)": "interfax.com.ua",
    "Interfax Ukraine": "interfax.com.ua",
    "Kyodo News (English)": "english.kyodonews.net",
    "Kyodo News": "english.kyodonews.net",
    "Novinite (Sofia News Agency)": "novinite.com",
    "Novinite": "novinite.com",
    "Yonhap News Agency (English)": "en.yna.co.kr",
    "Yonhap News Agency": "en.yna.co.kr",
    "AllAfrica": "allafrica.com",
    "Axios": "axios.com",
    "Arab News": "arabnews.com",
    "Australia Financial Review (AFR)": "afr.com",
    "Australia Financial Review": "afr.com",
    "Business Day (South Africa)": "businessday.co.za",
    "Business Day": "businessday.co.za",
    "Christian Science Monitor": "csmonitor.com",
    "Daily Nation (Kenya)": "nation.africa",
    "Daily Nation": "nation.africa",
    "Dawn": "dawn.com",
    "El Pa\u00eds English Edition": "english.elpais.com",
    "El Tiempo (English selections)": "eltiempo.com",
    "El Tiempo": "eltiempo.com",
    "Financial Times": "ft.com",
    "Folha de S.Paulo (English selections)": "folha.uol.com.br",
    "Folha de S.Paulo": "folha.uol.com.br",
    "Haaretz": "haaretz.com",
    "Handelsblatt Global": "handelsblatt.com",
    "Indian Express": "indianexpress.com",
    "Japan Times": "japantimes.co.jp",
    "Jerusalem Post": "jpost.com",
    "Korea JoongAng Daily": "koreajoongangdaily.joins.com",
    "L'Orient Today": "lorientlejour.com",
    "Los Angeles Times": "latimes.com",
    "Mail & Guardian": "mg.co.za",
    "Miami Herald": "miamiherald.com",
    "Nation.Africa (Daily Nation)": "nation.africa",
    "Nation.Africa": "nation.africa",
    "New York Times": "nytimes.com",
    "New Zealand Herald": "nzherald.co.nz",
    "O Globo (English selections)": "oglobo.globo.com",
    "O Globo": "oglobo.globo.com",
    "San Francisco Chronicle": "sfchronicle.com",
    "South China Morning Post": "scmp.com",
    "South China Morning Post (SCMP) China section": "scmp.com",
    "South China Morning Post (SCMP) Tech": "scmp.com",
    "Straits Times": "straitstimes.com",
    "Sydney Morning Herald": "smh.com.au",
    "Taipei Times": "taipeitimes.com",
    "Tampa Bay Times": "tampabay.com",
    "The Age": "theage.com.au",
    "The Asahi Shimbun (AJW)": "asahi.com",
    "The Asahi Shimbun": "asahi.com",
    "The Atlanta Journal-Constitution": "ajc.com",
    "The Boston Globe": "bostonglobe.com",
    "The Globe and Mail": "theglobeandmail.com",
    "The Guardian": "theguardian.com",
    "The Hindu": "thehindu.com",
    "The Hindu BusinessLine": "thehindubusinessline.com",
    "The Irish Times": "irishtimes.com",
    "The Jakarta Post": "thejakartapost.com",
    "The Korea Herald": "koreaherald.com",
    "The Kyiv Post": "kyivpost.com",
    "The Mainichi (English)": "mainichi.jp",
    "The Mainichi": "mainichi.jp",
    "The Monitor (Uganda)": "monitor.co.ug",
    "The Monitor": "monitor.co.ug",
    "The Namibian": "namibian.com.na",
    "The National (UAE)": "thenationalnews.com",
    "The National": "thenationalnews.com",
    "The Philadelphia Inquirer": "inquirer.com",
    "The Straits Times (World)": "straitstimes.com",
    "The Straits Times": "straitstimes.com",
    "The Sunday Times (UK)": "thetimes.co.uk",
    "The Sunday Times": "thetimes.co.uk",
    "The Times (UK)": "thetimes.co.uk",
    "The Times": "thetimes.co.uk",
    "Wall Street Journal": "wsj.com",
    "Washington Post": "washingtonpost.com",
    "i (inews)": "inews.co.uk",
    "i": "inews.co.uk",
    "Center for Public Integrity": "publicintegrity.org",
    "ProPublica": "propublica.org",
    "The Bureau of Investigative Journalism": "thebureauinvestigates.com",
    "The Markup": "themarkup.org",
    "CalMatters": "calmatters.org",
    "MinnPost": "minnpost.com",
    "Texas Tribune": "texastribune.org",
    "The City (NYC)": "thecity.nyc",
    "The City": "thecity.nyc",
    "The Salt Lake Tribune": "sltrib.com",
    "The 19th": "19thnews.org",
    "The Hechinger Report": "hechingerreport.org",
    "The Marshall Project": "themarshallproject.org",
    "The New Humanitarian": "thenewhumanitarian.org",
    "The Trace": "thetrace.org",
    "Bellingcat": "bellingcat.com",
    "Project Syndicate": "project-syndicate.org",
    "Euractiv": "euractiv.com",
    "Politico": "politico.com",
    "Politico Europe": "politico.eu",
    "Reporters Without Borders (RSF)": "rsf.org",
    "Reporters Without Borders": "rsf.org",
    "Stratfor (RANE)": "worldview.stratfor.com",
    "Stratfor": "worldview.stratfor.com",
    "ABC News Australia": "abc.net.au",
    "Al Jazeera English": "aljazeera.com",
    "BBC News": "bbc.com",
    "CBC News": "cbc.ca",
    "Deutsche Welle (DW)": "dw.com",
    "Deutsche Welle": "dw.com",
    "Euronews": "euronews.com",
    "France 24": "france24.com",
    "NHK World-Japan": "www3.nhk.or.jp",
    "NPR": "npr.org",
    "PBS NewsHour": "pbs.org",
    "RTE News": "rte.ie",
    "Radio New Zealand (RNZ)": "rnz.co.nz",
    "Radio New Zealand": "rnz.co.nz",
    "Voice of America": "voanews.com",
    "RTS / SRF Swiss Broadcasting (English pages)": "swissinfo.ch",
    "RTS / SRF Swiss Broadcasting": "swissinfo.ch",
    "Swissinfo.ch": "swissinfo.ch",
    "CIDRAP": "cidrap.umn.edu",
    "Americas Quarterly": "americasquarterly.org",
    "The Diplomat": "thediplomat.com",
    "The Diplomat (Asia-Pacific)": "thediplomat.com",
    "The Diplomat (Defense)": "thediplomat.com",
    "Al-Monitor": "al-monitor.com",
    "Middle East Eye": "middleeasteye.net",
    "The EastAfrican": "theeastafrican.co.ke",
    "Citizen Lab": "citizenlab.ca",
    "EU DisinfoLab": "disinfo.eu",
    "Graphika": "graphika.com",
    "Institute for Strategic Dialogue (ISD)": "isdglobal.org",
    "Institute for Strategic Dialogue": "isdglobal.org",
    "Nature News": "nature.com",
    "Science Magazine News": "science.org",
    "Jane's Defence": "janes.com",
    "Intelligence Online": "intelligenceonline.com",
    "Africa Confidential": "africa-confidential.com",
    "Argus Media": "argusmedia.com",
    "Aviation Week": "aviationweek.com",
    "BNE Intellinews": "intellinews.com",
    "Breaking Defense": "breakingdefense.com",
    "CSO Online": "csoonline.com",
    "Carbon Brief": "carbonbrief.org",
    "Clean Energy Wire": "cleanenergywire.org",
    "Climate Central": "climatecentral.org",
    "Climate Home News": "climatechangenews.com",
    "CyberScoop": "cyberscoop.com",
    "Dark Reading": "darkreading.com",
    "Defense News": "defensenews.com",
    "Defense One": "defenseone.com",
    "Devex": "devex.com",
    "E&E News": "eenews.net",
    "EdWeek": "edweek.org",
    "Energy Intelligence": "energyintel.com",
    "Euromoney": "euromoney.com",
    "FlightGlobal": "flightglobal.com",
    "Grist": "grist.org",
    "Health Policy Watch": "healthpolicy-watch.org",
    "IEEE Spectrum": "spectrum.ieee.org",
    "InSight Crime": "insightcrime.org",
    "Index on Censorship": "indexoncensorship.org",
    "Inside Climate News": "insideclimatenews.org",
    "Inside Higher Ed": "insidehighered.com",
    "Journal of Commerce (JOC)": "joc.com",
    "Journal of Commerce": "joc.com",
    "Kaiser Health News": "khn.org",
    "KrebsOnSecurity": "krebsonsecurity.com",
    "Lloyd's List": "lloydslist.com",
    "MIT Technology Review": "technologyreview.com",
    "Military Times": "militarytimes.com",
    "Mongabay": "mongabay.com",
    "Rest of World": "restofworld.org",
    "S&P Global Commodity Insights (Platts)": "spglobal.com",
    "S&P Global Commodity Insights": "spglobal.com",
    "S&P Global Market Intelligence News": "spglobal.com",
    "STAT News": "statnews.com",
    "SecurityWeek": "securityweek.com",
    "SpaceNews": "spacenews.com",
    "SpacePolicyOnline.com": "spacepolicyonline.com",
    "The Banker": "thebanker.com",
    "The Information": "theinformation.com",
    "The Record (Recorded Future News)": "therecord.media",
    "The Record": "therecord.media",
    "TradeWinds": "tradewindsnews.com",
    "Yale Climate Connections": "yaleclimateconnections.org",
    "gCaptain": "gcaptain.com",
    "CGTN": "cgtn.com",
    "Xinhua (English)": "xinhuanet.com",
    "Xinhua": "xinhuanet.com",
    "Ars Technica": "arstechnica.com",
    "Wired": "wired.com",
    "Atlantic Council": "atlanticcouncil.org",
    "Brookings Institution": "brookings.edu",
    "CEPA (Center for European Policy Analysis)": "cepa.org",
    "CEPA": "cepa.org",
    "CSIS": "csis.org",
    "Carnegie Endowment for International Peace": "carnegieendowment.org",
    "Chatham House": "chathamhouse.org",
    "Council on Foreign Relations (CFR)": "cfr.org",
    "Council on Foreign Relations": "cfr.org",
    "European Council on Foreign Relations (ECFR)": "ecfr.eu",
    "European Council on Foreign Relations": "ecfr.eu",
    "IISS": "iiss.org",
    "International Crisis Group": "crisisgroup.org",
    "Jamestown Foundation": "jamestown.org",
    "Lowy Institute (The Interpreter)": "lowyinstitute.org",
    "Lowy Institute": "lowyinstitute.org",
    "RAND": "rand.org",
    "RUSI": "rusi.org",
    "SIPRI": "sipri.org",
    "Stimson Center": "stimson.org",
    "The Africa Center (ACSS)": "africacenter.org",
    "The Africa Center": "africacenter.org",
    "Wilson Center": "wilsoncenter.org",
    "Institute for the Study of War (ISW)": "understandingwar.org",
    "Institute for the Study of War": "understandingwar.org",
    "CrowdStrike Blog": "crowdstrike.com",
    "Google Threat Analysis Group (TAG)": "blog.google",
    "Google Threat Analysis Group": "blog.google",
    "Mandiant (Google) Blog": "mandiant.com",
    "Mandiant": "mandiant.com",
    "Microsoft Security Blog": "microsoft.com",
    "Palo Alto Networks Unit 42": "unit42.paloaltonetworks.com",
    "Recorded Future (Research)": "recordedfuture.com",
    "Recorded Future": "recordedfuture.com",
    "SentinelOne Labs": "sentinelone.com",
    "The Economist": "economist.com",
};

// ============================================================================
// Extended source registry (merged with SOURCE_REGISTRY at runtime)
// ============================================================================

export const CURATED_SOURCES: Record<string, SourceEntry> = {
    "africanews.com": { displayName: "Africa News", tier: 2 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "alarabiya.net": { displayName: "Al Arabiya English", tier: 2 as 1 | 2 | 3, region: "Middle East", paywall: "free" },
    "channel4.com": { displayName: "Channel 4 News", tier: 2 as 1 | 2 | 3, region: "UK / Global", paywall: "free" },
    "channelnewsasia.com": { displayName: "Channel NewsAsia", tier: 2 as 1 | 2 | 3, region: "Asia-Pacific", paywall: "free" },
    "itv.com": { displayName: "ITV News", tier: 2 as 1 | 2 | 3, region: "UK", paywall: "free" },
    "news.sky.com": { displayName: "Sky News", tier: 2 as 1 | 2 | 3, region: "UK / Global", paywall: "free" },
    "caxinglobal.com": { displayName: "Caixin Global", tier: 3 as 1 | 2 | 3, region: "China / Global", paywall: "free" },
    "livemint.com": { displayName: "Mint", tier: 3 as 1 | 2 | 3, region: "India", paywall: "free" },
    "asia.nikkei.com": { displayName: "Nikkei Asia", tier: 3 as 1 | 2 | 3, region: "Asia", paywall: "hard" },
    "fivethirtyeight.com": { displayName: "FiveThirtyEight", tier: 3 as 1 | 2 | 3, region: "Politics & Data", paywall: "free" },
    "batimes.com.ar": { displayName: "Buenos Aires Times", tier: 3 as 1 | 2 | 3, region: "Argentina / Latin America", paywall: "free" },
    "notus.com": { displayName: "NOTUS", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "news24.com": { displayName: "News24", tier: 3 as 1 | 2 | 3, region: "South Africa", paywall: "free" },
    "taiwannews.com.tw": { displayName: "Taiwan News", tier: 3 as 1 | 2 | 3, region: "Taiwan", paywall: "free" },
    "thecable.ng": { displayName: "The Cable", tier: 3 as 1 | 2 | 3, region: "Nigeria", paywall: "free" },
    "thedispatch.com": { displayName: "The Dispatch", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "theprint.in": { displayName: "The Print", tier: 3 as 1 | 2 | 3, region: "India", paywall: "free" },
    "timesofisrael.com": { displayName: "The Times of Israel", tier: 3 as 1 | 2 | 3, region: "Israel / Middle East", paywall: "metered" },
    "independent.co.uk": { displayName: "The Independent", tier: 3 as 1 | 2 | 3, region: "UK", paywall: "free" },
    "eastasiaforum.org": { displayName: "East Asia Forum", tier: 2 as 1 | 2 | 3, region: "Asia-Pacific", paywall: "free" },
    "justsecurity.org": { displayName: "Just Security", tier: 2 as 1 | 2 | 3, region: "Law & Rights", paywall: "free" },
    "lawfaremedia.org": { displayName: "Lawfare", tier: 2 as 1 | 2 | 3, region: "National Security Law", paywall: "free" },
    "techpolicy.press": { displayName: "Tech Policy Press", tier: 2 as 1 | 2 | 3, region: "Tech Policy", paywall: "free" },
    "theconversation.com": { displayName: "The Conversation", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "warontherocks.com": { displayName: "War on the Rocks", tier: 2 as 1 | 2 | 3, region: "Defense & Security", paywall: "free", specialty: "defense" },
    "africacheck.org": { displayName: "Africa Check", tier: 3 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "fullfact.org": { displayName: "Full Fact", tier: 3 as 1 | 2 | 3, region: "UK", paywall: "free" },
    "politifact.com": { displayName: "PolitiFact", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "semafor.com": { displayName: "Semafor", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "france24.com": { displayName: "Agence France-Presse", tier: 1 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "apnews.com": { displayName: "Associated Press", tier: 1 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "bloomberg.com": { displayName: "Bloomberg News", tier: 1 as 1 | 2 | 3, region: "Business / Global", paywall: "hard", specialty: "finance" },
    "dpa-international.com": { displayName: "Deutsche Presse-Agentur", tier: 1 as 1 | 2 | 3, region: "Europe / Global", paywall: "free" },
    "reuters.com": { displayName: "Reuters", tier: 1 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "enisa.europa.eu": { displayName: "EU Agency for Cybersecurity", tier: 3 as 1 | 2 | 3, region: "EU", paywall: "free", specialty: "cybersecurity" },
    "cisa.gov": { displayName: "CISA Alerts", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free", specialty: "cybersecurity" },
    "ncsc.gov.uk": { displayName: "UK NCSC Blog", tier: 3 as 1 | 2 | 3, region: "UK", paywall: "free", specialty: "cybersecurity" },
    "opendemocracy.net": { displayName: "openDemocracy", tier: 3 as 1 | 2 | 3, region: "Global Democracy", paywall: "free" },
    "newlinesmag.com": { displayName: "New Lines Magazine", tier: 3 as 1 | 2 | 3, region: "Global South", paywall: "free" },
    "asiasentinel.com": { displayName: "Asia Sentinel", tier: 3 as 1 | 2 | 3, region: "Asia", paywall: "free" },
    "dailymaverick.co.za": { displayName: "Daily Maverick", tier: 3 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "euobserver.com": { displayName: "EUobserver", tier: 3 as 1 | 2 | 3, region: "European Union", paywall: "free" },
    "hromadske.ua": { displayName: "Hromadske International", tier: 3 as 1 | 2 | 3, region: "Ukraine", paywall: "free" },
    "kyivindependent.com": { displayName: "Kyiv Independent", tier: 3 as 1 | 2 | 3, region: "Ukraine", paywall: "free" },
    "meduza.io": { displayName: "Meduza", tier: 3 as 1 | 2 | 3, region: "Russia / Eurasia", paywall: "free" },
    "themoscowtimes.com": { displayName: "Moscow Times", tier: 3 as 1 | 2 | 3, region: "Russia", paywall: "free" },
    "novayagazeta.eu": { displayName: "Novaya Gazeta Europe", tier: 3 as 1 | 2 | 3, region: "Russia / Europe", paywall: "free" },
    "premiumtimesng.com": { displayName: "Premium Times", tier: 3 as 1 | 2 | 3, region: "Nigeria / Africa", paywall: "free" },
    "rappler.com": { displayName: "Rappler", tier: 3 as 1 | 2 | 3, region: "Philippines", paywall: "free" },
    "scroll.in": { displayName: "Scroll.in", tier: 3 as 1 | 2 | 3, region: "India", paywall: "free" },
    "thecontinent.org": { displayName: "The Continent", tier: 3 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "thewire.in": { displayName: "The Wire", tier: 3 as 1 | 2 | 3, region: "India", paywall: "free" },
    "timesca.com": { displayName: "Times of Central Asia", tier: 3 as 1 | 2 | 3, region: "Central Asia", paywall: "free" },
    "icij.org": { displayName: "ICIJ", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "investigate-europe.eu": { displayName: "Investigate Europe", tier: 2 as 1 | 2 | 3, region: "Europe", paywall: "free" },
    "occrp.org": { displayName: "OCCRP", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "balkaninsight.com": { displayName: "Balkan Insight", tier: 2 as 1 | 2 | 3, region: "Balkans", paywall: "free" },
    "birn.eu": { displayName: "Balkan Investigative Reporting Network", tier: 2 as 1 | 2 | 3, region: "Balkans", paywall: "free" },
    "codastory.com": { displayName: "Coda Story", tier: 2 as 1 | 2 | 3, region: "Information Warfare", paywall: "free" },
    "correctiv.org": { displayName: "Correctiv", tier: 2 as 1 | 2 | 3, region: "Germany / Europe", paywall: "free" },
    "elfaro.net": { displayName: "El Faro", tier: 2 as 1 | 2 | 3, region: "Central America", paywall: "free" },
    "followthemoney.ng": { displayName: "Follow the Money", tier: 2 as 1 | 2 | 3, region: "Netherlands / Europe", paywall: "free" },
    "ccreporting.org": { displayName: "The Center for Climate Reporting", tier: 2 as 1 | 2 | 3, region: "Climate", paywall: "free", specialty: "climate" },
    "theexamination.org": { displayName: "The Examination", tier: 2 as 1 | 2 | 3, region: "Environment / Health", paywall: "free", specialty: "health" },
    "revealnews.org": { displayName: "Reveal", tier: 2 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "theintercept.com": { displayName: "The Intercept", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "gothamist.com": { displayName: "Gothamist", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "spiegel.de": { displayName: "Der Spiegel International", tier: 2 as 1 | 2 | 3, region: "Europe / Global", paywall: "free" },
    "foreignpolicy.com": { displayName: "Foreign Policy", tier: 2 as 1 | 2 | 3, region: "Global Affairs", paywall: "metered" },
    "mondediplo.com": { displayName: "Le Monde diplomatique", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "time.com": { displayName: "TIME Magazine", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "theafricareport.com": { displayName: "The Africa Report", tier: 2 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "theatlantic.com": { displayName: "The Atlantic", tier: 2 as 1 | 2 | 3, region: "United States / Global", paywall: "hard" },
    "nybooks.com": { displayName: "The New York Review of Books", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "newyorker.com": { displayName: "The New Yorker", tier: 2 as 1 | 2 | 3, region: "United States / Global", paywall: "hard" },
    "bmj.com": { displayName: "BMJ News", tier: 3 as 1 | 2 | 3, region: "Health & Medicine", paywall: "free", specialty: "health" },
    "amnesty.org": { displayName: "Amnesty International", tier: 3 as 1 | 2 | 3, region: "Human Rights", paywall: "free" },
    "hrw.org": { displayName: "Human Rights Watch", tier: 3 as 1 | 2 | 3, region: "Human Rights", paywall: "free" },
    "focustaiwan.tw": { displayName: "Focus Taiwan", tier: 2 as 1 | 2 | 3, region: "Taiwan", paywall: "free" },
    "interfax.com.ua": { displayName: "Interfax Ukraine", tier: 2 as 1 | 2 | 3, region: "Ukraine", paywall: "free" },
    "english.kyodonews.net": { displayName: "Kyodo News", tier: 2 as 1 | 2 | 3, region: "Japan", paywall: "free" },
    "novinite.com": { displayName: "Novinite", tier: 2 as 1 | 2 | 3, region: "Bulgaria / Balkans", paywall: "free" },
    "en.yna.co.kr": { displayName: "Yonhap News Agency", tier: 2 as 1 | 2 | 3, region: "South Korea", paywall: "free" },
    "allafrica.com": { displayName: "AllAfrica", tier: 3 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "axios.com": { displayName: "Axios", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "arabnews.com": { displayName: "Arab News", tier: 3 as 1 | 2 | 3, region: "Middle East", paywall: "free" },
    "afr.com": { displayName: "Australia Financial Review", tier: 3 as 1 | 2 | 3, region: "Australia / Business", paywall: "free", specialty: "finance" },
    "businessday.co.za": { displayName: "Business Day", tier: 3 as 1 | 2 | 3, region: "South Africa", paywall: "free" },
    "csmonitor.com": { displayName: "Christian Science Monitor", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "nation.africa": { displayName: "Daily Nation", tier: 3 as 1 | 2 | 3, region: "Kenya", paywall: "free" },
    "dawn.com": { displayName: "Dawn", tier: 3 as 1 | 2 | 3, region: "South Asia", paywall: "free" },
    "english.elpais.com": { displayName: "El Pa\u00eds English Edition", tier: 3 as 1 | 2 | 3, region: "Europe / Latin America", paywall: "free" },
    "eltiempo.com": { displayName: "El Tiempo", tier: 3 as 1 | 2 | 3, region: "Colombia", paywall: "free" },
    "ft.com": { displayName: "Financial Times", tier: 3 as 1 | 2 | 3, region: "Global / Economics", paywall: "hard" },
    "folha.uol.com.br": { displayName: "Folha de S.Paulo", tier: 3 as 1 | 2 | 3, region: "Brazil", paywall: "free" },
    "haaretz.com": { displayName: "Haaretz", tier: 3 as 1 | 2 | 3, region: "Israel / Middle East", paywall: "metered" },
    "handelsblatt.com": { displayName: "Handelsblatt Global", tier: 3 as 1 | 2 | 3, region: "Germany / EU", paywall: "free" },
    "indianexpress.com": { displayName: "Indian Express", tier: 3 as 1 | 2 | 3, region: "India", paywall: "free" },
    "japantimes.co.jp": { displayName: "Japan Times", tier: 3 as 1 | 2 | 3, region: "Japan", paywall: "free" },
    "jpost.com": { displayName: "Jerusalem Post", tier: 3 as 1 | 2 | 3, region: "Israel / Middle East", paywall: "free" },
    "koreajoongangdaily.joins.com": { displayName: "Korea JoongAng Daily", tier: 3 as 1 | 2 | 3, region: "South Korea", paywall: "free" },
    "lorientlejour.com": { displayName: "L'Orient Today", tier: 3 as 1 | 2 | 3, region: "Lebanon / Middle East", paywall: "free" },
    "latimes.com": { displayName: "Los Angeles Times", tier: 3 as 1 | 2 | 3, region: "United States / Pacific Rim", paywall: "free" },
    "mg.co.za": { displayName: "Mail & Guardian", tier: 3 as 1 | 2 | 3, region: "Africa", paywall: "free" },
    "miamiherald.com": { displayName: "Miami Herald", tier: 3 as 1 | 2 | 3, region: "Latin America / US", paywall: "free" },
    "nytimes.com": { displayName: "New York Times", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "hard" },
    "nzherald.co.nz": { displayName: "New Zealand Herald", tier: 3 as 1 | 2 | 3, region: "New Zealand", paywall: "free" },
    "oglobo.globo.com": { displayName: "O Globo", tier: 3 as 1 | 2 | 3, region: "Brazil", paywall: "free" },
    "sfchronicle.com": { displayName: "San Francisco Chronicle", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "scmp.com": { displayName: "South China Morning Post", tier: 3 as 1 | 2 | 3, region: "China / Asia", paywall: "metered" },
    "straitstimes.com": { displayName: "Straits Times", tier: 3 as 1 | 2 | 3, region: "Southeast Asia", paywall: "free" },
    "smh.com.au": { displayName: "Sydney Morning Herald", tier: 3 as 1 | 2 | 3, region: "Australia", paywall: "free" },
    "taipeitimes.com": { displayName: "Taipei Times", tier: 3 as 1 | 2 | 3, region: "Taiwan", paywall: "free" },
    "tampabay.com": { displayName: "Tampa Bay Times", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "theage.com.au": { displayName: "The Age", tier: 3 as 1 | 2 | 3, region: "Australia", paywall: "free" },
    "asahi.com": { displayName: "The Asahi Shimbun", tier: 3 as 1 | 2 | 3, region: "Japan", paywall: "free" },
    "ajc.com": { displayName: "The Atlanta Journal-Constitution", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "bostonglobe.com": { displayName: "The Boston Globe", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "theglobeandmail.com": { displayName: "The Globe and Mail", tier: 3 as 1 | 2 | 3, region: "Canada", paywall: "hard" },
    "theguardian.com": { displayName: "The Guardian", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "thehindu.com": { displayName: "The Hindu", tier: 3 as 1 | 2 | 3, region: "India", paywall: "free" },
    "thehindubusinessline.com": { displayName: "The Hindu BusinessLine", tier: 3 as 1 | 2 | 3, region: "India / Business", paywall: "free", specialty: "finance" },
    "irishtimes.com": { displayName: "The Irish Times", tier: 3 as 1 | 2 | 3, region: "Ireland", paywall: "free" },
    "thejakartapost.com": { displayName: "The Jakarta Post", tier: 3 as 1 | 2 | 3, region: "Indonesia", paywall: "free" },
    "koreaherald.com": { displayName: "The Korea Herald", tier: 3 as 1 | 2 | 3, region: "South Korea", paywall: "free" },
    "kyivpost.com": { displayName: "The Kyiv Post", tier: 3 as 1 | 2 | 3, region: "Ukraine", paywall: "free" },
    "mainichi.jp": { displayName: "The Mainichi", tier: 3 as 1 | 2 | 3, region: "Japan", paywall: "free" },
    "monitor.co.ug": { displayName: "The Monitor", tier: 3 as 1 | 2 | 3, region: "East Africa", paywall: "free" },
    "namibian.com.na": { displayName: "The Namibian", tier: 3 as 1 | 2 | 3, region: "Namibia", paywall: "free" },
    "thenationalnews.com": { displayName: "The National", tier: 3 as 1 | 2 | 3, region: "Middle East", paywall: "free" },
    "inquirer.com": { displayName: "The Philadelphia Inquirer", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "thetimes.co.uk": { displayName: "The Sunday Times", tier: 3 as 1 | 2 | 3, region: "UK", paywall: "free" },
    "wsj.com": { displayName: "Wall Street Journal", tier: 3 as 1 | 2 | 3, region: "Global / Business", paywall: "hard", specialty: "finance" },
    "washingtonpost.com": { displayName: "Washington Post", tier: 3 as 1 | 2 | 3, region: "United States / Global", paywall: "hard" },
    "inews.co.uk": { displayName: "i", tier: 3 as 1 | 2 | 3, region: "UK", paywall: "free" },
    "publicintegrity.org": { displayName: "Center for Public Integrity", tier: 2 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "propublica.org": { displayName: "ProPublica", tier: 2 as 1 | 2 | 3, region: "United States / Global", paywall: "free" },
    "thebureauinvestigates.com": { displayName: "The Bureau of Investigative Journalism", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "themarkup.org": { displayName: "The Markup", tier: 2 as 1 | 2 | 3, region: "Technology", paywall: "free" },
    "calmatters.org": { displayName: "CalMatters", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "minnpost.com": { displayName: "MinnPost", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "texastribune.org": { displayName: "Texas Tribune", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "thecity.nyc": { displayName: "The City", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "sltrib.com": { displayName: "The Salt Lake Tribune", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "19thnews.org": { displayName: "The 19th", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "hechingerreport.org": { displayName: "The Hechinger Report", tier: 3 as 1 | 2 | 3, region: "Education", paywall: "free" },
    "themarshallproject.org": { displayName: "The Marshall Project", tier: 3 as 1 | 2 | 3, region: "Justice & Security", paywall: "free" },
    "thenewhumanitarian.org": { displayName: "The New Humanitarian", tier: 3 as 1 | 2 | 3, region: "Humanitarian Crises", paywall: "free" },
    "thetrace.org": { displayName: "The Trace", tier: 3 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "bellingcat.com": { displayName: "Bellingcat", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "project-syndicate.org": { displayName: "Project Syndicate", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "euractiv.com": { displayName: "Euractiv", tier: 3 as 1 | 2 | 3, region: "European Policy", paywall: "free" },
    "politico.com": { displayName: "Politico", tier: 3 as 1 | 2 | 3, region: "US / EU", paywall: "free" },
    "politico.eu": { displayName: "Politico Europe", tier: 3 as 1 | 2 | 3, region: "EU Politics", paywall: "free" },
    "rsf.org": { displayName: "Reporters Without Borders", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "worldview.stratfor.com": { displayName: "Stratfor", tier: 3 as 1 | 2 | 3, region: "Geopolitics", paywall: "free", specialty: "geopolitics" },
    "abc.net.au": { displayName: "ABC News Australia", tier: 2 as 1 | 2 | 3, region: "Australia / Global", paywall: "free" },
    "aljazeera.com": { displayName: "Al Jazeera English", tier: 2 as 1 | 2 | 3, region: "Global / Global South", paywall: "free" },
    "bbc.com": { displayName: "BBC News", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "cbc.ca": { displayName: "CBC News", tier: 2 as 1 | 2 | 3, region: "Canada", paywall: "free" },
    "dw.com": { displayName: "Deutsche Welle", tier: 2 as 1 | 2 | 3, region: "Europe / Global", paywall: "free" },
    "euronews.com": { displayName: "Euronews", tier: 2 as 1 | 2 | 3, region: "Europe", paywall: "free" },
    "www3.nhk.or.jp": { displayName: "NHK World-Japan", tier: 2 as 1 | 2 | 3, region: "Japan / Asia", paywall: "free" },
    "npr.org": { displayName: "NPR", tier: 2 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "pbs.org": { displayName: "PBS NewsHour", tier: 2 as 1 | 2 | 3, region: "United States", paywall: "free" },
    "rte.ie": { displayName: "RTE News", tier: 2 as 1 | 2 | 3, region: "Ireland", paywall: "free" },
    "rnz.co.nz": { displayName: "Radio New Zealand", tier: 2 as 1 | 2 | 3, region: "New Zealand", paywall: "free" },
    "voanews.com": { displayName: "Voice of America", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "swissinfo.ch": { displayName: "RTS / SRF Swiss Broadcasting", tier: 2 as 1 | 2 | 3, region: "Switzerland", paywall: "free" },
    "cidrap.umn.edu": { displayName: "CIDRAP", tier: 3 as 1 | 2 | 3, region: "Epidemics & Biosecurity", paywall: "free", specialty: "health" },
    "americasquarterly.org": { displayName: "Americas Quarterly", tier: 3 as 1 | 2 | 3, region: "Latin America", paywall: "free" },
    "thediplomat.com": { displayName: "The Diplomat", tier: 3 as 1 | 2 | 3, region: "Asia-Pacific", paywall: "free", specialty: "geopolitics" },
    "al-monitor.com": { displayName: "Al-Monitor", tier: 3 as 1 | 2 | 3, region: "Middle East", paywall: "free" },
    "middleeasteye.net": { displayName: "Middle East Eye", tier: 3 as 1 | 2 | 3, region: "Middle East", paywall: "free" },
    "theeastafrican.co.ke": { displayName: "The EastAfrican", tier: 3 as 1 | 2 | 3, region: "East Africa", paywall: "free" },
    "citizenlab.ca": { displayName: "Citizen Lab", tier: 2 as 1 | 2 | 3, region: "Cyber & Human Rights", paywall: "free" },
    "disinfo.eu": { displayName: "EU DisinfoLab", tier: 2 as 1 | 2 | 3, region: "Europe", paywall: "free" },
    "graphika.com": { displayName: "Graphika", tier: 2 as 1 | 2 | 3, region: "Information Operations", paywall: "free" },
    "isdglobal.org": { displayName: "Institute for Strategic Dialogue", tier: 2 as 1 | 2 | 3, region: "Extremism & Disinfo", paywall: "free" },
    "nature.com": { displayName: "Nature News", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "metered" },
    "science.org": { displayName: "Science Magazine News", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "metered" },
    "janes.com": { displayName: "Jane's Defence", tier: 3 as 1 | 2 | 3, region: "Defense & Security", paywall: "hard", specialty: "defense" },
    "intelligenceonline.com": { displayName: "Intelligence Online", tier: 3 as 1 | 2 | 3, region: "Global Security", paywall: "hard" },
    "africa-confidential.com": { displayName: "Africa Confidential", tier: 3 as 1 | 2 | 3, region: "Africa Politics", paywall: "hard" },
    "argusmedia.com": { displayName: "Argus Media", tier: 3 as 1 | 2 | 3, region: "Energy Markets", paywall: "free", specialty: "climate" },
    "aviationweek.com": { displayName: "Aviation Week", tier: 3 as 1 | 2 | 3, region: "Aviation & Defense", paywall: "hard", specialty: "defense" },
    "intellinews.com": { displayName: "BNE Intellinews", tier: 3 as 1 | 2 | 3, region: "Eastern Europe / Eurasia", paywall: "free" },
    "breakingdefense.com": { displayName: "Breaking Defense", tier: 3 as 1 | 2 | 3, region: "Defense Industry", paywall: "free", specialty: "defense" },
    "csoonline.com": { displayName: "CSO Online", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "carbonbrief.org": { displayName: "Carbon Brief", tier: 3 as 1 | 2 | 3, region: "Climate Policy", paywall: "free", specialty: "climate" },
    "cleanenergywire.org": { displayName: "Clean Energy Wire", tier: 3 as 1 | 2 | 3, region: "Energy Transition", paywall: "free", specialty: "climate" },
    "climatecentral.org": { displayName: "Climate Central", tier: 3 as 1 | 2 | 3, region: "Climate", paywall: "free", specialty: "climate" },
    "climatechangenews.com": { displayName: "Climate Home News", tier: 3 as 1 | 2 | 3, region: "Climate Diplomacy", paywall: "free", specialty: "climate" },
    "cyberscoop.com": { displayName: "CyberScoop", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "darkreading.com": { displayName: "Dark Reading", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "defensenews.com": { displayName: "Defense News", tier: 3 as 1 | 2 | 3, region: "Defense & Military", paywall: "free", specialty: "defense" },
    "defenseone.com": { displayName: "Defense One", tier: 3 as 1 | 2 | 3, region: "Defense & Policy", paywall: "free", specialty: "defense" },
    "devex.com": { displayName: "Devex", tier: 3 as 1 | 2 | 3, region: "Global Development", paywall: "free" },
    "eenews.net": { displayName: "E&E News", tier: 3 as 1 | 2 | 3, region: "Energy & Environment", paywall: "free", specialty: "climate" },
    "edweek.org": { displayName: "EdWeek", tier: 3 as 1 | 2 | 3, region: "Education", paywall: "free" },
    "energyintel.com": { displayName: "Energy Intelligence", tier: 3 as 1 | 2 | 3, region: "Energy & Geopolitics", paywall: "hard", specialty: "climate" },
    "euromoney.com": { displayName: "Euromoney", tier: 3 as 1 | 2 | 3, region: "Finance", paywall: "hard", specialty: "finance" },
    "flightglobal.com": { displayName: "FlightGlobal", tier: 3 as 1 | 2 | 3, region: "Aviation", paywall: "free" },
    "grist.org": { displayName: "Grist", tier: 3 as 1 | 2 | 3, region: "Climate", paywall: "free", specialty: "climate" },
    "healthpolicy-watch.org": { displayName: "Health Policy Watch", tier: 3 as 1 | 2 | 3, region: "Global Health", paywall: "free", specialty: "health" },
    "spectrum.ieee.org": { displayName: "IEEE Spectrum", tier: 3 as 1 | 2 | 3, region: "Technology / Engineering", paywall: "free" },
    "insightcrime.org": { displayName: "InSight Crime", tier: 3 as 1 | 2 | 3, region: "Crime & Security", paywall: "free" },
    "indexoncensorship.org": { displayName: "Index on Censorship", tier: 3 as 1 | 2 | 3, region: "Free Expression", paywall: "free" },
    "insideclimatenews.org": { displayName: "Inside Climate News", tier: 3 as 1 | 2 | 3, region: "Climate", paywall: "free", specialty: "climate" },
    "insidehighered.com": { displayName: "Inside Higher Ed", tier: 3 as 1 | 2 | 3, region: "Education", paywall: "free" },
    "joc.com": { displayName: "Journal of Commerce", tier: 3 as 1 | 2 | 3, region: "Supply Chain", paywall: "free" },
    "khn.org": { displayName: "Kaiser Health News", tier: 3 as 1 | 2 | 3, region: "Health Policy", paywall: "free", specialty: "health" },
    "krebsonsecurity.com": { displayName: "KrebsOnSecurity", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free", specialty: "cybersecurity" },
    "lloydslist.com": { displayName: "Lloyd's List", tier: 3 as 1 | 2 | 3, region: "Maritime", paywall: "hard" },
    "technologyreview.com": { displayName: "MIT Technology Review", tier: 3 as 1 | 2 | 3, region: "Technology", paywall: "metered" },
    "militarytimes.com": { displayName: "Military Times", tier: 3 as 1 | 2 | 3, region: "Defense & Military", paywall: "free", specialty: "defense" },
    "mongabay.com": { displayName: "Mongabay", tier: 3 as 1 | 2 | 3, region: "Environment", paywall: "free" },
    "restofworld.org": { displayName: "Rest of World", tier: 3 as 1 | 2 | 3, region: "Global Technology", paywall: "free" },
    "spglobal.com": { displayName: "S&P Global Commodity Insights", tier: 3 as 1 | 2 | 3, region: "Energy & Commodities", paywall: "hard", specialty: "climate" },
    "statnews.com": { displayName: "STAT News", tier: 3 as 1 | 2 | 3, region: "Health & Science", paywall: "metered", specialty: "health" },
    "securityweek.com": { displayName: "SecurityWeek", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "spacenews.com": { displayName: "SpaceNews", tier: 3 as 1 | 2 | 3, region: "Space", paywall: "free" },
    "spacepolicyonline.com": { displayName: "SpacePolicyOnline.com", tier: 3 as 1 | 2 | 3, region: "Space Policy", paywall: "free" },
    "thebanker.com": { displayName: "The Banker", tier: 3 as 1 | 2 | 3, region: "Finance", paywall: "hard", specialty: "finance" },
    "theinformation.com": { displayName: "The Information", tier: 3 as 1 | 2 | 3, region: "Technology / Business", paywall: "hard", specialty: "finance" },
    "therecord.media": { displayName: "The Record", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free", specialty: "cybersecurity" },
    "tradewindsnews.com": { displayName: "TradeWinds", tier: 3 as 1 | 2 | 3, region: "Maritime", paywall: "hard" },
    "yaleclimateconnections.org": { displayName: "Yale Climate Connections", tier: 3 as 1 | 2 | 3, region: "Climate & Science", paywall: "free", specialty: "climate" },
    "gcaptain.com": { displayName: "gCaptain", tier: 3 as 1 | 2 | 3, region: "Maritime", paywall: "free" },
    "cgtn.com": { displayName: "CGTN", tier: 3 as 1 | 2 | 3, region: "China / Global", paywall: "free" },
    "xinhuanet.com": { displayName: "Xinhua", tier: 3 as 1 | 2 | 3, region: "Global", paywall: "free" },
    "arstechnica.com": { displayName: "Ars Technica", tier: 3 as 1 | 2 | 3, region: "Technology", paywall: "free", specialty: "tech" },
    "wired.com": { displayName: "Wired", tier: 3 as 1 | 2 | 3, region: "Technology & Society", paywall: "metered", specialty: "tech" },
    "atlanticcouncil.org": { displayName: "Atlantic Council", tier: 2 as 1 | 2 | 3, region: "Global Security", paywall: "free", specialty: "cybersecurity" },
    "brookings.edu": { displayName: "Brookings Institution", tier: 2 as 1 | 2 | 3, region: "Policy / Global", paywall: "free" },
    "cepa.org": { displayName: "CEPA", tier: 2 as 1 | 2 | 3, region: "Europe / Russia", paywall: "free" },
    "csis.org": { displayName: "CSIS", tier: 2 as 1 | 2 | 3, region: "Global Security", paywall: "free" },
    "carnegieendowment.org": { displayName: "Carnegie Endowment for International Peace", tier: 2 as 1 | 2 | 3, region: "Global Affairs", paywall: "free" },
    "chathamhouse.org": { displayName: "Chatham House", tier: 2 as 1 | 2 | 3, region: "International Affairs", paywall: "free" },
    "cfr.org": { displayName: "Council on Foreign Relations", tier: 2 as 1 | 2 | 3, region: "Foreign Policy", paywall: "free" },
    "ecfr.eu": { displayName: "European Council on Foreign Relations", tier: 2 as 1 | 2 | 3, region: "Europe & Global Affairs", paywall: "free" },
    "iiss.org": { displayName: "IISS", tier: 2 as 1 | 2 | 3, region: "Defense & Security", paywall: "free", specialty: "defense" },
    "crisisgroup.org": { displayName: "International Crisis Group", tier: 2 as 1 | 2 | 3, region: "Global Conflict", paywall: "free" },
    "jamestown.org": { displayName: "Jamestown Foundation", tier: 2 as 1 | 2 | 3, region: "Eurasia / Security", paywall: "free" },
    "lowyinstitute.org": { displayName: "Lowy Institute", tier: 2 as 1 | 2 | 3, region: "Asia-Pacific", paywall: "free" },
    "rand.org": { displayName: "RAND", tier: 2 as 1 | 2 | 3, region: "Security & Policy", paywall: "free" },
    "rusi.org": { displayName: "RUSI", tier: 2 as 1 | 2 | 3, region: "Defense & Security", paywall: "free", specialty: "defense" },
    "sipri.org": { displayName: "SIPRI", tier: 2 as 1 | 2 | 3, region: "Arms & Conflict", paywall: "free" },
    "stimson.org": { displayName: "Stimson Center", tier: 2 as 1 | 2 | 3, region: "Security & Climate", paywall: "free", specialty: "climate" },
    "africacenter.org": { displayName: "The Africa Center", tier: 2 as 1 | 2 | 3, region: "Africa Security", paywall: "free" },
    "wilsoncenter.org": { displayName: "Wilson Center", tier: 2 as 1 | 2 | 3, region: "Global Affairs", paywall: "free" },
    "understandingwar.org": { displayName: "Institute for the Study of War", tier: 2 as 1 | 2 | 3, region: "Conflict & Security", paywall: "free" },
    "crowdstrike.com": { displayName: "CrowdStrike Blog", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "blog.google": { displayName: "Google Threat Analysis Group", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "mandiant.com": { displayName: "Mandiant", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "microsoft.com": { displayName: "Microsoft Security Blog", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "unit42.paloaltonetworks.com": { displayName: "Palo Alto Networks Unit 42", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "recordedfuture.com": { displayName: "Recorded Future", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "sentinelone.com": { displayName: "SentinelOne Labs", tier: 3 as 1 | 2 | 3, region: "Cybersecurity", paywall: "free" },
    "economist.com": { displayName: "The Economist", tier: 2 as 1 | 2 | 3, region: "Global", paywall: "hard" },
};
